import numpy as np
import os 
from gtda.diagrams import Amplitude, PersistenceEntropy, NumberOfPoints, ComplexPolynomial
import pandas as pd
n_jobs = -1
directory = "./data/pDRed13EV41kHzStride2"
savingDirectory  = "./data/ufeaturesPDRed13EV41kHzStride2.csv"
maxDistance = 4000
homology_dimensions = [0, 1, 2]
featuresWithBettiPoint = {
    'sampleName': [],
    'parkinson?':[],
    'AentropyH0':[],
    'AentropyH1':[],
    'AentropyH2':[],
    'AlandscapeAmplitudeH0':[],
    'AlandscapeAmplitudeH1':[],
    'AlandscapeAmplitudeH2':[],
    'AnumberOfPoints':[],
    'AbettiAmplitude1H0':[],
    'AbettiAmplitude2H0':[],
    'AbettiAmplitude3H0':[],
    'AbettiAmplitude4H0':[],
    'AbettiAmplitude5H0':[],
    'AbettiAmplitude6H0':[],
    'AbettiAmplitude7H0':[],
    'AbettiAmplitude8H0':[],
    'AbettiAmplitude9H0':[],
    'AbettiAmplitude10H0':[],
    'AbettiAmplitude11H0':[],
    'AbettiAmplitude12H0':[],
    'AbettiAmplitude13H0':[],
    'AbettiAmplitude14H0':[],
    'AbettiAmplitude15H0':[],
    'AbettiAmplitude16H0':[],
    'AbettiAmplitude17H0':[],
    'AbettiAmplitude18H0':[],
    'AbettiAmplitude19H0':[],
    'AbettiAmplitude20H0':[],
    'AbettiAmplitude21H0':[],
    'AbettiAmplitude22H0':[],
    'AbettiAmplitude23H0':[],
    'AbettiAmplitude24H0':[],
    'AbettiAmplitude25H0':[],
    'AbettiAmplitude26H0':[],
    'AbettiAmplitude27H0':[],
    'AbettiAmplitude28H0':[],
    'AbettiAmplitude29H0':[],
    'AbettiAmplitude30H0':[],
    'AbettiAmplitude31H0':[],
    'AbettiAmplitude32H0':[],
    'AbettiAmplitude33H0':[],
    'AbettiAmplitude34H0':[],
    'AbettiAmplitude35H0':[],
    'AbettiAmplitude36H0':[],
    'AbettiAmplitude37H0':[],
    'AbettiAmplitude38H0':[],
    'AbettiAmplitude39H0':[],
    'AbettiAmplitude40H0':[],
    'AbettiAmplitude41H0':[],
    'AbettiAmplitude42H0':[],
    'AbettiAmplitude43H0':[],
    'AbettiAmplitude44H0':[],
    'AbettiAmplitude45H0':[],
    'AbettiAmplitude46H0':[],
    'AbettiAmplitude47H0':[],
    'AbettiAmplitude48H0':[],
    'AbettiAmplitude49H0':[],
    'AbettiAmplitude50H0':[],
    'AbettiAmplitude51H0':[],
    'AbettiAmplitude52H0':[],
    'AbettiAmplitude53H0':[],
    'AbettiAmplitude54H0':[],
    'AbettiAmplitude55H0':[],
    'AbettiAmplitude56H0':[],
    'AbettiAmplitude57H0':[],
    'AbettiAmplitude58H0':[],
    'AbettiAmplitude59H0':[],
    'AbettiAmplitude60H0':[],
    'AbettiAmplitude61H0':[],
    'AbettiAmplitude62H0':[],
    'AbettiAmplitude63H0':[],
    'AbettiAmplitude64H0':[],
    'AbettiAmplitude65H0':[],
    'AbettiAmplitude66H0':[],
    'AbettiAmplitude67H0':[],
    'AbettiAmplitude68H0':[],
    'AbettiAmplitude69H0':[],
    'AbettiAmplitude70H0':[],
    'AbettiAmplitude71H0':[],
    'AbettiAmplitude72H0':[],
    'AbettiAmplitude73H0':[],
    'AbettiAmplitude74H0':[],
    'AbettiAmplitude75H0':[],
    'AbettiAmplitude76H0':[],
    'AbettiAmplitude77H0':[],
    'AbettiAmplitude78H0':[],
    'AbettiAmplitude79H0':[],
    'AbettiAmplitude80H0':[],
    'AbettiAmplitude81H0':[],
    'AbettiAmplitude82H0':[],
    'AbettiAmplitude83H0':[],
    'AbettiAmplitude84H0':[],
    'AbettiAmplitude85H0':[],
    'AbettiAmplitude86H0':[],
    'AbettiAmplitude87H0':[],
    'AbettiAmplitude88H0':[],
    'AbettiAmplitude89H0':[],
    'AbettiAmplitude90H0':[],
    'AbettiAmplitude91H0':[],
    'AbettiAmplitude92H0':[],
    'AbettiAmplitude93H0':[],
    'AbettiAmplitude94H0':[],
    'AbettiAmplitude95H0':[],
    'AbettiAmplitude96H0':[],
    'AbettiAmplitude97H0':[],
    'AbettiAmplitude98H0':[],
    'AbettiAmplitude99H0':[],
    'AbettiAmplitude100H0':[],
    'AbettiAmplitude1H1':[],
    'AbettiAmplitude2H1':[],
    'AbettiAmplitude3H1':[],
    'AbettiAmplitude4H1':[],
    'AbettiAmplitude5H1':[],
    'AbettiAmplitude6H1':[],
    'AbettiAmplitude7H1':[],
    'AbettiAmplitude8H1':[],
    'AbettiAmplitude9H1':[],
    'AbettiAmplitude10H1':[],
    'AbettiAmplitude11H1':[],
    'AbettiAmplitude12H1':[],
    'AbettiAmplitude13H1':[],
    'AbettiAmplitude14H1':[],
    'AbettiAmplitude15H1':[],
    'AbettiAmplitude16H1':[],
    'AbettiAmplitude17H1':[],
    'AbettiAmplitude18H1':[],
    'AbettiAmplitude19H1':[],
    'AbettiAmplitude20H1':[],
    'AbettiAmplitude21H1':[],
    'AbettiAmplitude22H1':[],
    'AbettiAmplitude23H1':[],
    'AbettiAmplitude24H1':[],
    'AbettiAmplitude25H1':[],
    'AbettiAmplitude26H1':[],
    'AbettiAmplitude27H1':[],
    'AbettiAmplitude28H1':[],
    'AbettiAmplitude29H1':[],
    'AbettiAmplitude30H1':[],
    'AbettiAmplitude31H1':[],
    'AbettiAmplitude32H1':[],
    'AbettiAmplitude33H1':[],
    'AbettiAmplitude34H1':[],
    'AbettiAmplitude35H1':[],
    'AbettiAmplitude36H1':[],
    'AbettiAmplitude37H1':[],
    'AbettiAmplitude38H1':[],
    'AbettiAmplitude39H1':[],
    'AbettiAmplitude40H1':[],
    'AbettiAmplitude41H1':[],
    'AbettiAmplitude42H1':[],
    'AbettiAmplitude43H1':[],
    'AbettiAmplitude44H1':[],
    'AbettiAmplitude45H1':[],
    'AbettiAmplitude46H1':[],
    'AbettiAmplitude47H1':[],
    'AbettiAmplitude48H1':[],
    'AbettiAmplitude49H1':[],
    'AbettiAmplitude50H1':[],
    'AbettiAmplitude51H1':[],
    'AbettiAmplitude52H1':[],
    'AbettiAmplitude53H1':[],
    'AbettiAmplitude54H1':[],
    'AbettiAmplitude55H1':[],
    'AbettiAmplitude56H1':[],
    'AbettiAmplitude57H1':[],
    'AbettiAmplitude58H1':[],
    'AbettiAmplitude59H1':[],
    'AbettiAmplitude60H1':[],
    'AbettiAmplitude61H1':[],
    'AbettiAmplitude62H1':[],
    'AbettiAmplitude63H1':[],
    'AbettiAmplitude64H1':[],
    'AbettiAmplitude65H1':[],
    'AbettiAmplitude66H1':[],
    'AbettiAmplitude67H1':[],
    'AbettiAmplitude68H1':[],
    'AbettiAmplitude69H1':[],
    'AbettiAmplitude70H1':[],
    'AbettiAmplitude71H1':[],
    'AbettiAmplitude72H1':[],
    'AbettiAmplitude73H1':[],
    'AbettiAmplitude74H1':[],
    'AbettiAmplitude75H1':[],
    'AbettiAmplitude76H1':[],
    'AbettiAmplitude77H1':[],
    'AbettiAmplitude78H1':[],
    'AbettiAmplitude79H1':[],
    'AbettiAmplitude80H1':[],
    'AbettiAmplitude81H1':[],
    'AbettiAmplitude82H1':[],
    'AbettiAmplitude83H1':[],
    'AbettiAmplitude84H1':[],
    'AbettiAmplitude85H1':[],
    'AbettiAmplitude86H1':[],
    'AbettiAmplitude87H1':[],
    'AbettiAmplitude88H1':[],
    'AbettiAmplitude89H1':[],
    'AbettiAmplitude90H1':[],
    'AbettiAmplitude91H1':[],
    'AbettiAmplitude92H1':[],
    'AbettiAmplitude93H1':[],
    'AbettiAmplitude94H1':[],
    'AbettiAmplitude95H1':[],
    'AbettiAmplitude96H1':[],
    'AbettiAmplitude97H1':[],
    'AbettiAmplitude98H1':[],
    'AbettiAmplitude99H1':[],
    'AbettiAmplitude100H1':[],
    'AbettiAmplitude1H2':[],
    'AbettiAmplitude2H2':[],
    'AbettiAmplitude3H2':[],
    'AbettiAmplitude4H2':[],
    'AbettiAmplitude5H2':[],
    'AbettiAmplitude6H2':[],
    'AbettiAmplitude7H2':[],
    'AbettiAmplitude8H2':[],
    'AbettiAmplitude9H2':[],
    'AbettiAmplitude10H2':[],
    'AbettiAmplitude11H2':[],
    'AbettiAmplitude12H2':[],
    'AbettiAmplitude13H2':[],
    'AbettiAmplitude14H2':[],
    'AbettiAmplitude15H2':[],
    'AbettiAmplitude16H2':[],
    'AbettiAmplitude17H2':[],
    'AbettiAmplitude18H2':[],
    'AbettiAmplitude19H2':[],
    'AbettiAmplitude20H2':[],
    'AbettiAmplitude21H2':[],
    'AbettiAmplitude22H2':[],
    'AbettiAmplitude23H2':[],
    'AbettiAmplitude24H2':[],
    'AbettiAmplitude25H2':[],
    'AbettiAmplitude26H2':[],
    'AbettiAmplitude27H2':[],
    'AbettiAmplitude28H2':[],
    'AbettiAmplitude29H2':[],
    'AbettiAmplitude30H2':[],
    'AbettiAmplitude31H2':[],
    'AbettiAmplitude32H2':[],
    'AbettiAmplitude33H2':[],
    'AbettiAmplitude34H2':[],
    'AbettiAmplitude35H2':[],
    'AbettiAmplitude36H2':[],
    'AbettiAmplitude37H2':[],
    'AbettiAmplitude38H2':[],
    'AbettiAmplitude39H2':[],
    'AbettiAmplitude40H2':[],
    'AbettiAmplitude41H2':[],
    'AbettiAmplitude42H2':[],
    'AbettiAmplitude43H2':[],
    'AbettiAmplitude44H2':[],
    'AbettiAmplitude45H2':[],
    'AbettiAmplitude46H2':[],
    'AbettiAmplitude47H2':[],
    'AbettiAmplitude48H2':[],
    'AbettiAmplitude49H2':[],
    'AbettiAmplitude50H2':[],
    'AbettiAmplitude51H2':[],
    'AbettiAmplitude52H2':[],
    'AbettiAmplitude53H2':[],
    'AbettiAmplitude54H2':[],
    'AbettiAmplitude55H2':[],
    'AbettiAmplitude56H2':[],
    'AbettiAmplitude57H2':[],
    'AbettiAmplitude58H2':[],
    'AbettiAmplitude59H2':[],
    'AbettiAmplitude60H2':[],
    'AbettiAmplitude61H2':[],
    'AbettiAmplitude62H2':[],
    'AbettiAmplitude63H2':[],
    'AbettiAmplitude64H2':[],
    'AbettiAmplitude65H2':[],
    'AbettiAmplitude66H2':[],
    'AbettiAmplitude67H2':[],
    'AbettiAmplitude68H2':[],
    'AbettiAmplitude69H2':[],
    'AbettiAmplitude70H2':[],
    'AbettiAmplitude71H2':[],
    'AbettiAmplitude72H2':[],
    'AbettiAmplitude73H2':[],
    'AbettiAmplitude74H2':[],
    'AbettiAmplitude75H2':[],
    'AbettiAmplitude76H2':[],
    'AbettiAmplitude77H2':[],
    'AbettiAmplitude78H2':[],
    'AbettiAmplitude79H2':[],
    'AbettiAmplitude80H2':[],
    'AbettiAmplitude81H2':[],
    'AbettiAmplitude82H2':[],
    'AbettiAmplitude83H2':[],
    'AbettiAmplitude84H2':[],
    'AbettiAmplitude85H2':[],
    'AbettiAmplitude86H2':[],
    'AbettiAmplitude87H2':[],
    'AbettiAmplitude88H2':[],
    'AbettiAmplitude89H2':[],
    'AbettiAmplitude90H2':[],
    'AbettiAmplitude91H2':[],
    'AbettiAmplitude92H2':[],
    'AbettiAmplitude93H2':[],
    'AbettiAmplitude94H2':[],
    'AbettiAmplitude95H2':[],
    'AbettiAmplitude96H2':[],
    'AbettiAmplitude97H2':[],
    'AbettiAmplitude98H2':[],
    'AbettiAmplitude99H2':[],
    'AbettiAmplitude100H2':[],
    'AcomplexPolinomialCoef1H0': [],
    'AcomplexPolinomialCoef2H0': [],
    'AcomplexPolinomialCoef3H0': [],
    'AcomplexPolinomialCoef4H0': [],
    'AcomplexPolinomialCoef5H0': [],
    'AcomplexPolinomialCoef6H0': [],
    'AcomplexPolinomialCoef7H0': [],
    'AcomplexPolinomialCoef8H0': [],
    'AcomplexPolinomialCoef9H0': [],
    'AcomplexPolinomialCoef10H0': [],
    'AcomplexPolinomialCoef1H1': [],
    'AcomplexPolinomialCoef2H1': [],
    'AcomplexPolinomialCoef3H1': [],
    'AcomplexPolinomialCoef4H1': [],
    'AcomplexPolinomialCoef5H1': [],
    'AcomplexPolinomialCoef6H1': [],
    'AcomplexPolinomialCoef7H1': [],
    'AcomplexPolinomialCoef8H1': [],
    'AcomplexPolinomialCoef9H1': [],
    'AcomplexPolinomialCoef10H1': [],
    'AcomplexPolinomialCoef1H2': [],
    'AcomplexPolinomialCoef2H2': [],
    'AcomplexPolinomialCoef3H2': [],
    'AcomplexPolinomialCoef4H2': [],
    'AcomplexPolinomialCoef5H2': [],
    'AcomplexPolinomialCoef6H2': [],
    'AcomplexPolinomialCoef7H2': [],
    'AcomplexPolinomialCoef8H2': [],
    'AcomplexPolinomialCoef9H2': [],
    'AcomplexPolinomialCoef10H2': [],
    'EentropyH0':[],
    'EentropyH1':[],
    'EentropyH2':[],
    'ElandscapeAmplitudeH0':[],
    'ElandscapeAmplitudeH1':[],
    'ElandscapeAmplitudeH2':[],
    'EnumberOfPoints':[],
    'EbettiAmplitude1H0':[],
    'EbettiAmplitude2H0':[],
    'EbettiAmplitude3H0':[],
    'EbettiAmplitude4H0':[],
    'EbettiAmplitude5H0':[],
    'EbettiAmplitude6H0':[],
    'EbettiAmplitude7H0':[],
    'EbettiAmplitude8H0':[],
    'EbettiAmplitude9H0':[],
    'EbettiAmplitude10H0':[],
    'EbettiAmplitude11H0':[],
    'EbettiAmplitude12H0':[],
    'EbettiAmplitude13H0':[],
    'EbettiAmplitude14H0':[],
    'EbettiAmplitude15H0':[],
    'EbettiAmplitude16H0':[],
    'EbettiAmplitude17H0':[],
    'EbettiAmplitude18H0':[],
    'EbettiAmplitude19H0':[],
    'EbettiAmplitude20H0':[],
    'EbettiAmplitude21H0':[],
    'EbettiAmplitude22H0':[],
    'EbettiAmplitude23H0':[],
    'EbettiAmplitude24H0':[],
    'EbettiAmplitude25H0':[],
    'EbettiAmplitude26H0':[],
    'EbettiAmplitude27H0':[],
    'EbettiAmplitude28H0':[],
    'EbettiAmplitude29H0':[],
    'EbettiAmplitude30H0':[],
    'EbettiAmplitude31H0':[],
    'EbettiAmplitude32H0':[],
    'EbettiAmplitude33H0':[],
    'EbettiAmplitude34H0':[],
    'EbettiAmplitude35H0':[],
    'EbettiAmplitude36H0':[],
    'EbettiAmplitude37H0':[],
    'EbettiAmplitude38H0':[],
    'EbettiAmplitude39H0':[],
    'EbettiAmplitude40H0':[],
    'EbettiAmplitude41H0':[],
    'EbettiAmplitude42H0':[],
    'EbettiAmplitude43H0':[],
    'EbettiAmplitude44H0':[],
    'EbettiAmplitude45H0':[],
    'EbettiAmplitude46H0':[],
    'EbettiAmplitude47H0':[],
    'EbettiAmplitude48H0':[],
    'EbettiAmplitude49H0':[],
    'EbettiAmplitude50H0':[],
    'EbettiAmplitude51H0':[],
    'EbettiAmplitude52H0':[],
    'EbettiAmplitude53H0':[],
    'EbettiAmplitude54H0':[],
    'EbettiAmplitude55H0':[],
    'EbettiAmplitude56H0':[],
    'EbettiAmplitude57H0':[],
    'EbettiAmplitude58H0':[],
    'EbettiAmplitude59H0':[],
    'EbettiAmplitude60H0':[],
    'EbettiAmplitude61H0':[],
    'EbettiAmplitude62H0':[],
    'EbettiAmplitude63H0':[],
    'EbettiAmplitude64H0':[],
    'EbettiAmplitude65H0':[],
    'EbettiAmplitude66H0':[],
    'EbettiAmplitude67H0':[],
    'EbettiAmplitude68H0':[],
    'EbettiAmplitude69H0':[],
    'EbettiAmplitude70H0':[],
    'EbettiAmplitude71H0':[],
    'EbettiAmplitude72H0':[],
    'EbettiAmplitude73H0':[],
    'EbettiAmplitude74H0':[],
    'EbettiAmplitude75H0':[],
    'EbettiAmplitude76H0':[],
    'EbettiAmplitude77H0':[],
    'EbettiAmplitude78H0':[],
    'EbettiAmplitude79H0':[],
    'EbettiAmplitude80H0':[],
    'EbettiAmplitude81H0':[],
    'EbettiAmplitude82H0':[],
    'EbettiAmplitude83H0':[],
    'EbettiAmplitude84H0':[],
    'EbettiAmplitude85H0':[],
    'EbettiAmplitude86H0':[],
    'EbettiAmplitude87H0':[],
    'EbettiAmplitude88H0':[],
    'EbettiAmplitude89H0':[],
    'EbettiAmplitude90H0':[],
    'EbettiAmplitude91H0':[],
    'EbettiAmplitude92H0':[],
    'EbettiAmplitude93H0':[],
    'EbettiAmplitude94H0':[],
    'EbettiAmplitude95H0':[],
    'EbettiAmplitude96H0':[],
    'EbettiAmplitude97H0':[],
    'EbettiAmplitude98H0':[],
    'EbettiAmplitude99H0':[],
    'EbettiAmplitude100H0':[],
    'EbettiAmplitude1H1':[],
    'EbettiAmplitude2H1':[],
    'EbettiAmplitude3H1':[],
    'EbettiAmplitude4H1':[],
    'EbettiAmplitude5H1':[],
    'EbettiAmplitude6H1':[],
    'EbettiAmplitude7H1':[],
    'EbettiAmplitude8H1':[],
    'EbettiAmplitude9H1':[],
    'EbettiAmplitude10H1':[],
    'EbettiAmplitude11H1':[],
    'EbettiAmplitude12H1':[],
    'EbettiAmplitude13H1':[],
    'EbettiAmplitude14H1':[],
    'EbettiAmplitude15H1':[],
    'EbettiAmplitude16H1':[],
    'EbettiAmplitude17H1':[],
    'EbettiAmplitude18H1':[],
    'EbettiAmplitude19H1':[],
    'EbettiAmplitude20H1':[],
    'EbettiAmplitude21H1':[],
    'EbettiAmplitude22H1':[],
    'EbettiAmplitude23H1':[],
    'EbettiAmplitude24H1':[],
    'EbettiAmplitude25H1':[],
    'EbettiAmplitude26H1':[],
    'EbettiAmplitude27H1':[],
    'EbettiAmplitude28H1':[],
    'EbettiAmplitude29H1':[],
    'EbettiAmplitude30H1':[],
    'EbettiAmplitude31H1':[],
    'EbettiAmplitude32H1':[],
    'EbettiAmplitude33H1':[],
    'EbettiAmplitude34H1':[],
    'EbettiAmplitude35H1':[],
    'EbettiAmplitude36H1':[],
    'EbettiAmplitude37H1':[],
    'EbettiAmplitude38H1':[],
    'EbettiAmplitude39H1':[],
    'EbettiAmplitude40H1':[],
    'EbettiAmplitude41H1':[],
    'EbettiAmplitude42H1':[],
    'EbettiAmplitude43H1':[],
    'EbettiAmplitude44H1':[],
    'EbettiAmplitude45H1':[],
    'EbettiAmplitude46H1':[],
    'EbettiAmplitude47H1':[],
    'EbettiAmplitude48H1':[],
    'EbettiAmplitude49H1':[],
    'EbettiAmplitude50H1':[],
    'EbettiAmplitude51H1':[],
    'EbettiAmplitude52H1':[],
    'EbettiAmplitude53H1':[],
    'EbettiAmplitude54H1':[],
    'EbettiAmplitude55H1':[],
    'EbettiAmplitude56H1':[],
    'EbettiAmplitude57H1':[],
    'EbettiAmplitude58H1':[],
    'EbettiAmplitude59H1':[],
    'EbettiAmplitude60H1':[],
    'EbettiAmplitude61H1':[],
    'EbettiAmplitude62H1':[],
    'EbettiAmplitude63H1':[],
    'EbettiAmplitude64H1':[],
    'EbettiAmplitude65H1':[],
    'EbettiAmplitude66H1':[],
    'EbettiAmplitude67H1':[],
    'EbettiAmplitude68H1':[],
    'EbettiAmplitude69H1':[],
    'EbettiAmplitude70H1':[],
    'EbettiAmplitude71H1':[],
    'EbettiAmplitude72H1':[],
    'EbettiAmplitude73H1':[],
    'EbettiAmplitude74H1':[],
    'EbettiAmplitude75H1':[],
    'EbettiAmplitude76H1':[],
    'EbettiAmplitude77H1':[],
    'EbettiAmplitude78H1':[],
    'EbettiAmplitude79H1':[],
    'EbettiAmplitude80H1':[],
    'EbettiAmplitude81H1':[],
    'EbettiAmplitude82H1':[],
    'EbettiAmplitude83H1':[],
    'EbettiAmplitude84H1':[],
    'EbettiAmplitude85H1':[],
    'EbettiAmplitude86H1':[],
    'EbettiAmplitude87H1':[],
    'EbettiAmplitude88H1':[],
    'EbettiAmplitude89H1':[],
    'EbettiAmplitude90H1':[],
    'EbettiAmplitude91H1':[],
    'EbettiAmplitude92H1':[],
    'EbettiAmplitude93H1':[],
    'EbettiAmplitude94H1':[],
    'EbettiAmplitude95H1':[],
    'EbettiAmplitude96H1':[],
    'EbettiAmplitude97H1':[],
    'EbettiAmplitude98H1':[],
    'EbettiAmplitude99H1':[],
    'EbettiAmplitude100H1':[],
    'EbettiAmplitude1H2':[],
    'EbettiAmplitude2H2':[],
    'EbettiAmplitude3H2':[],
    'EbettiAmplitude4H2':[],
    'EbettiAmplitude5H2':[],
    'EbettiAmplitude6H2':[],
    'EbettiAmplitude7H2':[],
    'EbettiAmplitude8H2':[],
    'EbettiAmplitude9H2':[],
    'EbettiAmplitude10H2':[],
    'EbettiAmplitude11H2':[],
    'EbettiAmplitude12H2':[],
    'EbettiAmplitude13H2':[],
    'EbettiAmplitude14H2':[],
    'EbettiAmplitude15H2':[],
    'EbettiAmplitude16H2':[],
    'EbettiAmplitude17H2':[],
    'EbettiAmplitude18H2':[],
    'EbettiAmplitude19H2':[],
    'EbettiAmplitude20H2':[],
    'EbettiAmplitude21H2':[],
    'EbettiAmplitude22H2':[],
    'EbettiAmplitude23H2':[],
    'EbettiAmplitude24H2':[],
    'EbettiAmplitude25H2':[],
    'EbettiAmplitude26H2':[],
    'EbettiAmplitude27H2':[],
    'EbettiAmplitude28H2':[],
    'EbettiAmplitude29H2':[],
    'EbettiAmplitude30H2':[],
    'EbettiAmplitude31H2':[],
    'EbettiAmplitude32H2':[],
    'EbettiAmplitude33H2':[],
    'EbettiAmplitude34H2':[],
    'EbettiAmplitude35H2':[],
    'EbettiAmplitude36H2':[],
    'EbettiAmplitude37H2':[],
    'EbettiAmplitude38H2':[],
    'EbettiAmplitude39H2':[],
    'EbettiAmplitude40H2':[],
    'EbettiAmplitude41H2':[],
    'EbettiAmplitude42H2':[],
    'EbettiAmplitude43H2':[],
    'EbettiAmplitude44H2':[],
    'EbettiAmplitude45H2':[],
    'EbettiAmplitude46H2':[],
    'EbettiAmplitude47H2':[],
    'EbettiAmplitude48H2':[],
    'EbettiAmplitude49H2':[],
    'EbettiAmplitude50H2':[],
    'EbettiAmplitude51H2':[],
    'EbettiAmplitude52H2':[],
    'EbettiAmplitude53H2':[],
    'EbettiAmplitude54H2':[],
    'EbettiAmplitude55H2':[],
    'EbettiAmplitude56H2':[],
    'EbettiAmplitude57H2':[],
    'EbettiAmplitude58H2':[],
    'EbettiAmplitude59H2':[],
    'EbettiAmplitude60H2':[],
    'EbettiAmplitude61H2':[],
    'EbettiAmplitude62H2':[],
    'EbettiAmplitude63H2':[],
    'EbettiAmplitude64H2':[],
    'EbettiAmplitude65H2':[],
    'EbettiAmplitude66H2':[],
    'EbettiAmplitude67H2':[],
    'EbettiAmplitude68H2':[],
    'EbettiAmplitude69H2':[],
    'EbettiAmplitude70H2':[],
    'EbettiAmplitude71H2':[],
    'EbettiAmplitude72H2':[],
    'EbettiAmplitude73H2':[],
    'EbettiAmplitude74H2':[],
    'EbettiAmplitude75H2':[],
    'EbettiAmplitude76H2':[],
    'EbettiAmplitude77H2':[],
    'EbettiAmplitude78H2':[],
    'EbettiAmplitude79H2':[],
    'EbettiAmplitude80H2':[],
    'EbettiAmplitude81H2':[],
    'EbettiAmplitude82H2':[],
    'EbettiAmplitude83H2':[],
    'EbettiAmplitude84H2':[],
    'EbettiAmplitude85H2':[],
    'EbettiAmplitude86H2':[],
    'EbettiAmplitude87H2':[],
    'EbettiAmplitude88H2':[],
    'EbettiAmplitude89H2':[],
    'EbettiAmplitude90H2':[],
    'EbettiAmplitude91H2':[],
    'EbettiAmplitude92H2':[],
    'EbettiAmplitude93H2':[],
    'EbettiAmplitude94H2':[],
    'EbettiAmplitude95H2':[],
    'EbettiAmplitude96H2':[],
    'EbettiAmplitude97H2':[],
    'EbettiAmplitude98H2':[],
    'EbettiAmplitude99H2':[],
    'EbettiAmplitude100H2':[],
    'EcomplexPolinomialCoef1H0': [],
    'EcomplexPolinomialCoef2H0': [],
    'EcomplexPolinomialCoef3H0': [],
    'EcomplexPolinomialCoef4H0': [],
    'EcomplexPolinomialCoef5H0': [],
    'EcomplexPolinomialCoef6H0': [],
    'EcomplexPolinomialCoef7H0': [],
    'EcomplexPolinomialCoef8H0': [],
    'EcomplexPolinomialCoef9H0': [],
    'EcomplexPolinomialCoef10H0': [],
    'EcomplexPolinomialCoef1H1': [],
    'EcomplexPolinomialCoef2H1': [],
    'EcomplexPolinomialCoef3H1': [],
    'EcomplexPolinomialCoef4H1': [],
    'EcomplexPolinomialCoef5H1': [],
    'EcomplexPolinomialCoef6H1': [],
    'EcomplexPolinomialCoef7H1': [],
    'EcomplexPolinomialCoef8H1': [],
    'EcomplexPolinomialCoef9H1': [],
    'EcomplexPolinomialCoef10H1': [],
    'EcomplexPolinomialCoef1H2': [],
    'EcomplexPolinomialCoef2H2': [],
    'EcomplexPolinomialCoef3H2': [],
    'EcomplexPolinomialCoef4H2': [],
    'EcomplexPolinomialCoef5H2': [],
    'EcomplexPolinomialCoef6H2': [],
    'EcomplexPolinomialCoef7H2': [],
    'EcomplexPolinomialCoef8H2': [],
    'EcomplexPolinomialCoef9H2': [],
    'EcomplexPolinomialCoef10H2': [],
    'IentropyH0':[],
    'IentropyH1':[],
    'IentropyH2':[],
    'IlandscapeAmplitudeH0':[],
    'IlandscapeAmplitudeH1':[],
    'IlandscapeAmplitudeH2':[],
    'InumberOfPoints':[],
    'IbettiAmplitude1H0':[],
    'IbettiAmplitude2H0':[],
    'IbettiAmplitude3H0':[],
    'IbettiAmplitude4H0':[],
    'IbettiAmplitude5H0':[],
    'IbettiAmplitude6H0':[],
    'IbettiAmplitude7H0':[],
    'IbettiAmplitude8H0':[],
    'IbettiAmplitude9H0':[],
    'IbettiAmplitude10H0':[],
    'IbettiAmplitude11H0':[],
    'IbettiAmplitude12H0':[],
    'IbettiAmplitude13H0':[],
    'IbettiAmplitude14H0':[],
    'IbettiAmplitude15H0':[],
    'IbettiAmplitude16H0':[],
    'IbettiAmplitude17H0':[],
    'IbettiAmplitude18H0':[],
    'IbettiAmplitude19H0':[],
    'IbettiAmplitude20H0':[],
    'IbettiAmplitude21H0':[],
    'IbettiAmplitude22H0':[],
    'IbettiAmplitude23H0':[],
    'IbettiAmplitude24H0':[],
    'IbettiAmplitude25H0':[],
    'IbettiAmplitude26H0':[],
    'IbettiAmplitude27H0':[],
    'IbettiAmplitude28H0':[],
    'IbettiAmplitude29H0':[],
    'IbettiAmplitude30H0':[],
    'IbettiAmplitude31H0':[],
    'IbettiAmplitude32H0':[],
    'IbettiAmplitude33H0':[],
    'IbettiAmplitude34H0':[],
    'IbettiAmplitude35H0':[],
    'IbettiAmplitude36H0':[],
    'IbettiAmplitude37H0':[],
    'IbettiAmplitude38H0':[],
    'IbettiAmplitude39H0':[],
    'IbettiAmplitude40H0':[],
    'IbettiAmplitude41H0':[],
    'IbettiAmplitude42H0':[],
    'IbettiAmplitude43H0':[],
    'IbettiAmplitude44H0':[],
    'IbettiAmplitude45H0':[],
    'IbettiAmplitude46H0':[],
    'IbettiAmplitude47H0':[],
    'IbettiAmplitude48H0':[],
    'IbettiAmplitude49H0':[],
    'IbettiAmplitude50H0':[],
    'IbettiAmplitude51H0':[],
    'IbettiAmplitude52H0':[],
    'IbettiAmplitude53H0':[],
    'IbettiAmplitude54H0':[],
    'IbettiAmplitude55H0':[],
    'IbettiAmplitude56H0':[],
    'IbettiAmplitude57H0':[],
    'IbettiAmplitude58H0':[],
    'IbettiAmplitude59H0':[],
    'IbettiAmplitude60H0':[],
    'IbettiAmplitude61H0':[],
    'IbettiAmplitude62H0':[],
    'IbettiAmplitude63H0':[],
    'IbettiAmplitude64H0':[],
    'IbettiAmplitude65H0':[],
    'IbettiAmplitude66H0':[],
    'IbettiAmplitude67H0':[],
    'IbettiAmplitude68H0':[],
    'IbettiAmplitude69H0':[],
    'IbettiAmplitude70H0':[],
    'IbettiAmplitude71H0':[],
    'IbettiAmplitude72H0':[],
    'IbettiAmplitude73H0':[],
    'IbettiAmplitude74H0':[],
    'IbettiAmplitude75H0':[],
    'IbettiAmplitude76H0':[],
    'IbettiAmplitude77H0':[],
    'IbettiAmplitude78H0':[],
    'IbettiAmplitude79H0':[],
    'IbettiAmplitude80H0':[],
    'IbettiAmplitude81H0':[],
    'IbettiAmplitude82H0':[],
    'IbettiAmplitude83H0':[],
    'IbettiAmplitude84H0':[],
    'IbettiAmplitude85H0':[],
    'IbettiAmplitude86H0':[],
    'IbettiAmplitude87H0':[],
    'IbettiAmplitude88H0':[],
    'IbettiAmplitude89H0':[],
    'IbettiAmplitude90H0':[],
    'IbettiAmplitude91H0':[],
    'IbettiAmplitude92H0':[],
    'IbettiAmplitude93H0':[],
    'IbettiAmplitude94H0':[],
    'IbettiAmplitude95H0':[],
    'IbettiAmplitude96H0':[],
    'IbettiAmplitude97H0':[],
    'IbettiAmplitude98H0':[],
    'IbettiAmplitude99H0':[],
    'IbettiAmplitude100H0':[],
    'IbettiAmplitude1H1':[],
    'IbettiAmplitude2H1':[],
    'IbettiAmplitude3H1':[],
    'IbettiAmplitude4H1':[],
    'IbettiAmplitude5H1':[],
    'IbettiAmplitude6H1':[],
    'IbettiAmplitude7H1':[],
    'IbettiAmplitude8H1':[],
    'IbettiAmplitude9H1':[],
    'IbettiAmplitude10H1':[],
    'IbettiAmplitude11H1':[],
    'IbettiAmplitude12H1':[],
    'IbettiAmplitude13H1':[],
    'IbettiAmplitude14H1':[],
    'IbettiAmplitude15H1':[],
    'IbettiAmplitude16H1':[],
    'IbettiAmplitude17H1':[],
    'IbettiAmplitude18H1':[],
    'IbettiAmplitude19H1':[],
    'IbettiAmplitude20H1':[],
    'IbettiAmplitude21H1':[],
    'IbettiAmplitude22H1':[],
    'IbettiAmplitude23H1':[],
    'IbettiAmplitude24H1':[],
    'IbettiAmplitude25H1':[],
    'IbettiAmplitude26H1':[],
    'IbettiAmplitude27H1':[],
    'IbettiAmplitude28H1':[],
    'IbettiAmplitude29H1':[],
    'IbettiAmplitude30H1':[],
    'IbettiAmplitude31H1':[],
    'IbettiAmplitude32H1':[],
    'IbettiAmplitude33H1':[],
    'IbettiAmplitude34H1':[],
    'IbettiAmplitude35H1':[],
    'IbettiAmplitude36H1':[],
    'IbettiAmplitude37H1':[],
    'IbettiAmplitude38H1':[],
    'IbettiAmplitude39H1':[],
    'IbettiAmplitude40H1':[],
    'IbettiAmplitude41H1':[],
    'IbettiAmplitude42H1':[],
    'IbettiAmplitude43H1':[],
    'IbettiAmplitude44H1':[],
    'IbettiAmplitude45H1':[],
    'IbettiAmplitude46H1':[],
    'IbettiAmplitude47H1':[],
    'IbettiAmplitude48H1':[],
    'IbettiAmplitude49H1':[],
    'IbettiAmplitude50H1':[],
    'IbettiAmplitude51H1':[],
    'IbettiAmplitude52H1':[],
    'IbettiAmplitude53H1':[],
    'IbettiAmplitude54H1':[],
    'IbettiAmplitude55H1':[],
    'IbettiAmplitude56H1':[],
    'IbettiAmplitude57H1':[],
    'IbettiAmplitude58H1':[],
    'IbettiAmplitude59H1':[],
    'IbettiAmplitude60H1':[],
    'IbettiAmplitude61H1':[],
    'IbettiAmplitude62H1':[],
    'IbettiAmplitude63H1':[],
    'IbettiAmplitude64H1':[],
    'IbettiAmplitude65H1':[],
    'IbettiAmplitude66H1':[],
    'IbettiAmplitude67H1':[],
    'IbettiAmplitude68H1':[],
    'IbettiAmplitude69H1':[],
    'IbettiAmplitude70H1':[],
    'IbettiAmplitude71H1':[],
    'IbettiAmplitude72H1':[],
    'IbettiAmplitude73H1':[],
    'IbettiAmplitude74H1':[],
    'IbettiAmplitude75H1':[],
    'IbettiAmplitude76H1':[],
    'IbettiAmplitude77H1':[],
    'IbettiAmplitude78H1':[],
    'IbettiAmplitude79H1':[],
    'IbettiAmplitude80H1':[],
    'IbettiAmplitude81H1':[],
    'IbettiAmplitude82H1':[],
    'IbettiAmplitude83H1':[],
    'IbettiAmplitude84H1':[],
    'IbettiAmplitude85H1':[],
    'IbettiAmplitude86H1':[],
    'IbettiAmplitude87H1':[],
    'IbettiAmplitude88H1':[],
    'IbettiAmplitude89H1':[],
    'IbettiAmplitude90H1':[],
    'IbettiAmplitude91H1':[],
    'IbettiAmplitude92H1':[],
    'IbettiAmplitude93H1':[],
    'IbettiAmplitude94H1':[],
    'IbettiAmplitude95H1':[],
    'IbettiAmplitude96H1':[],
    'IbettiAmplitude97H1':[],
    'IbettiAmplitude98H1':[],
    'IbettiAmplitude99H1':[],
    'IbettiAmplitude100H1':[],
    'IbettiAmplitude1H2':[],
    'IbettiAmplitude2H2':[],
    'IbettiAmplitude3H2':[],
    'IbettiAmplitude4H2':[],
    'IbettiAmplitude5H2':[],
    'IbettiAmplitude6H2':[],
    'IbettiAmplitude7H2':[],
    'IbettiAmplitude8H2':[],
    'IbettiAmplitude9H2':[],
    'IbettiAmplitude10H2':[],
    'IbettiAmplitude11H2':[],
    'IbettiAmplitude12H2':[],
    'IbettiAmplitude13H2':[],
    'IbettiAmplitude14H2':[],
    'IbettiAmplitude15H2':[],
    'IbettiAmplitude16H2':[],
    'IbettiAmplitude17H2':[],
    'IbettiAmplitude18H2':[],
    'IbettiAmplitude19H2':[],
    'IbettiAmplitude20H2':[],
    'IbettiAmplitude21H2':[],
    'IbettiAmplitude22H2':[],
    'IbettiAmplitude23H2':[],
    'IbettiAmplitude24H2':[],
    'IbettiAmplitude25H2':[],
    'IbettiAmplitude26H2':[],
    'IbettiAmplitude27H2':[],
    'IbettiAmplitude28H2':[],
    'IbettiAmplitude29H2':[],
    'IbettiAmplitude30H2':[],
    'IbettiAmplitude31H2':[],
    'IbettiAmplitude32H2':[],
    'IbettiAmplitude33H2':[],
    'IbettiAmplitude34H2':[],
    'IbettiAmplitude35H2':[],
    'IbettiAmplitude36H2':[],
    'IbettiAmplitude37H2':[],
    'IbettiAmplitude38H2':[],
    'IbettiAmplitude39H2':[],
    'IbettiAmplitude40H2':[],
    'IbettiAmplitude41H2':[],
    'IbettiAmplitude42H2':[],
    'IbettiAmplitude43H2':[],
    'IbettiAmplitude44H2':[],
    'IbettiAmplitude45H2':[],
    'IbettiAmplitude46H2':[],
    'IbettiAmplitude47H2':[],
    'IbettiAmplitude48H2':[],
    'IbettiAmplitude49H2':[],
    'IbettiAmplitude50H2':[],
    'IbettiAmplitude51H2':[],
    'IbettiAmplitude52H2':[],
    'IbettiAmplitude53H2':[],
    'IbettiAmplitude54H2':[],
    'IbettiAmplitude55H2':[],
    'IbettiAmplitude56H2':[],
    'IbettiAmplitude57H2':[],
    'IbettiAmplitude58H2':[],
    'IbettiAmplitude59H2':[],
    'IbettiAmplitude60H2':[],
    'IbettiAmplitude61H2':[],
    'IbettiAmplitude62H2':[],
    'IbettiAmplitude63H2':[],
    'IbettiAmplitude64H2':[],
    'IbettiAmplitude65H2':[],
    'IbettiAmplitude66H2':[],
    'IbettiAmplitude67H2':[],
    'IbettiAmplitude68H2':[],
    'IbettiAmplitude69H2':[],
    'IbettiAmplitude70H2':[],
    'IbettiAmplitude71H2':[],
    'IbettiAmplitude72H2':[],
    'IbettiAmplitude73H2':[],
    'IbettiAmplitude74H2':[],
    'IbettiAmplitude75H2':[],
    'IbettiAmplitude76H2':[],
    'IbettiAmplitude77H2':[],
    'IbettiAmplitude78H2':[],
    'IbettiAmplitude79H2':[],
    'IbettiAmplitude80H2':[],
    'IbettiAmplitude81H2':[],
    'IbettiAmplitude82H2':[],
    'IbettiAmplitude83H2':[],
    'IbettiAmplitude84H2':[],
    'IbettiAmplitude85H2':[],
    'IbettiAmplitude86H2':[],
    'IbettiAmplitude87H2':[],
    'IbettiAmplitude88H2':[],
    'IbettiAmplitude89H2':[],
    'IbettiAmplitude90H2':[],
    'IbettiAmplitude91H2':[],
    'IbettiAmplitude92H2':[],
    'IbettiAmplitude93H2':[],
    'IbettiAmplitude94H2':[],
    'IbettiAmplitude95H2':[],
    'IbettiAmplitude96H2':[],
    'IbettiAmplitude97H2':[],
    'IbettiAmplitude98H2':[],
    'IbettiAmplitude99H2':[],
    'IbettiAmplitude100H2':[],
    'IcomplexPolinomialCoef1H0': [],
    'IcomplexPolinomialCoef2H0': [],
    'IcomplexPolinomialCoef3H0': [],
    'IcomplexPolinomialCoef4H0': [],
    'IcomplexPolinomialCoef5H0': [],
    'IcomplexPolinomialCoef6H0': [],
    'IcomplexPolinomialCoef7H0': [],
    'IcomplexPolinomialCoef8H0': [],
    'IcomplexPolinomialCoef9H0': [],
    'IcomplexPolinomialCoef10H0': [],
    'IcomplexPolinomialCoef1H1': [],
    'IcomplexPolinomialCoef2H1': [],
    'IcomplexPolinomialCoef3H1': [],
    'IcomplexPolinomialCoef4H1': [],
    'IcomplexPolinomialCoef5H1': [],
    'IcomplexPolinomialCoef6H1': [],
    'IcomplexPolinomialCoef7H1': [],
    'IcomplexPolinomialCoef8H1': [],
    'IcomplexPolinomialCoef9H1': [],
    'IcomplexPolinomialCoef10H1': [],
    'IcomplexPolinomialCoef1H2': [],
    'IcomplexPolinomialCoef2H2': [],
    'IcomplexPolinomialCoef3H2': [],
    'IcomplexPolinomialCoef4H2': [],
    'IcomplexPolinomialCoef5H2': [],
    'IcomplexPolinomialCoef6H2': [],
    'IcomplexPolinomialCoef7H2': [],
    'IcomplexPolinomialCoef8H2': [],
    'IcomplexPolinomialCoef9H2': [],
    'IcomplexPolinomialCoef10H2': [],
    'OentropyH0':[],
    'OentropyH1':[],
    'OentropyH2':[],
    'OlandscapeAmplitudeH0':[],
    'OlandscapeAmplitudeH1':[],
    'OlandscapeAmplitudeH2':[],
    'OnumberOfPoints':[],
    'ObettiAmplitude1H0':[],
    'ObettiAmplitude2H0':[],
    'ObettiAmplitude3H0':[],
    'ObettiAmplitude4H0':[],
    'ObettiAmplitude5H0':[],
    'ObettiAmplitude6H0':[],
    'ObettiAmplitude7H0':[],
    'ObettiAmplitude8H0':[],
    'ObettiAmplitude9H0':[],
    'ObettiAmplitude10H0':[],
    'ObettiAmplitude11H0':[],
    'ObettiAmplitude12H0':[],
    'ObettiAmplitude13H0':[],
    'ObettiAmplitude14H0':[],
    'ObettiAmplitude15H0':[],
    'ObettiAmplitude16H0':[],
    'ObettiAmplitude17H0':[],
    'ObettiAmplitude18H0':[],
    'ObettiAmplitude19H0':[],
    'ObettiAmplitude20H0':[],
    'ObettiAmplitude21H0':[],
    'ObettiAmplitude22H0':[],
    'ObettiAmplitude23H0':[],
    'ObettiAmplitude24H0':[],
    'ObettiAmplitude25H0':[],
    'ObettiAmplitude26H0':[],
    'ObettiAmplitude27H0':[],
    'ObettiAmplitude28H0':[],
    'ObettiAmplitude29H0':[],
    'ObettiAmplitude30H0':[],
    'ObettiAmplitude31H0':[],
    'ObettiAmplitude32H0':[],
    'ObettiAmplitude33H0':[],
    'ObettiAmplitude34H0':[],
    'ObettiAmplitude35H0':[],
    'ObettiAmplitude36H0':[],
    'ObettiAmplitude37H0':[],
    'ObettiAmplitude38H0':[],
    'ObettiAmplitude39H0':[],
    'ObettiAmplitude40H0':[],
    'ObettiAmplitude41H0':[],
    'ObettiAmplitude42H0':[],
    'ObettiAmplitude43H0':[],
    'ObettiAmplitude44H0':[],
    'ObettiAmplitude45H0':[],
    'ObettiAmplitude46H0':[],
    'ObettiAmplitude47H0':[],
    'ObettiAmplitude48H0':[],
    'ObettiAmplitude49H0':[],
    'ObettiAmplitude50H0':[],
    'ObettiAmplitude51H0':[],
    'ObettiAmplitude52H0':[],
    'ObettiAmplitude53H0':[],
    'ObettiAmplitude54H0':[],
    'ObettiAmplitude55H0':[],
    'ObettiAmplitude56H0':[],
    'ObettiAmplitude57H0':[],
    'ObettiAmplitude58H0':[],
    'ObettiAmplitude59H0':[],
    'ObettiAmplitude60H0':[],
    'ObettiAmplitude61H0':[],
    'ObettiAmplitude62H0':[],
    'ObettiAmplitude63H0':[],
    'ObettiAmplitude64H0':[],
    'ObettiAmplitude65H0':[],
    'ObettiAmplitude66H0':[],
    'ObettiAmplitude67H0':[],
    'ObettiAmplitude68H0':[],
    'ObettiAmplitude69H0':[],
    'ObettiAmplitude70H0':[],
    'ObettiAmplitude71H0':[],
    'ObettiAmplitude72H0':[],
    'ObettiAmplitude73H0':[],
    'ObettiAmplitude74H0':[],
    'ObettiAmplitude75H0':[],
    'ObettiAmplitude76H0':[],
    'ObettiAmplitude77H0':[],
    'ObettiAmplitude78H0':[],
    'ObettiAmplitude79H0':[],
    'ObettiAmplitude80H0':[],
    'ObettiAmplitude81H0':[],
    'ObettiAmplitude82H0':[],
    'ObettiAmplitude83H0':[],
    'ObettiAmplitude84H0':[],
    'ObettiAmplitude85H0':[],
    'ObettiAmplitude86H0':[],
    'ObettiAmplitude87H0':[],
    'ObettiAmplitude88H0':[],
    'ObettiAmplitude89H0':[],
    'ObettiAmplitude90H0':[],
    'ObettiAmplitude91H0':[],
    'ObettiAmplitude92H0':[],
    'ObettiAmplitude93H0':[],
    'ObettiAmplitude94H0':[],
    'ObettiAmplitude95H0':[],
    'ObettiAmplitude96H0':[],
    'ObettiAmplitude97H0':[],
    'ObettiAmplitude98H0':[],
    'ObettiAmplitude99H0':[],
    'ObettiAmplitude100H0':[],
    'ObettiAmplitude1H1':[],
    'ObettiAmplitude2H1':[],
    'ObettiAmplitude3H1':[],
    'ObettiAmplitude4H1':[],
    'ObettiAmplitude5H1':[],
    'ObettiAmplitude6H1':[],
    'ObettiAmplitude7H1':[],
    'ObettiAmplitude8H1':[],
    'ObettiAmplitude9H1':[],
    'ObettiAmplitude10H1':[],
    'ObettiAmplitude11H1':[],
    'ObettiAmplitude12H1':[],
    'ObettiAmplitude13H1':[],
    'ObettiAmplitude14H1':[],
    'ObettiAmplitude15H1':[],
    'ObettiAmplitude16H1':[],
    'ObettiAmplitude17H1':[],
    'ObettiAmplitude18H1':[],
    'ObettiAmplitude19H1':[],
    'ObettiAmplitude20H1':[],
    'ObettiAmplitude21H1':[],
    'ObettiAmplitude22H1':[],
    'ObettiAmplitude23H1':[],
    'ObettiAmplitude24H1':[],
    'ObettiAmplitude25H1':[],
    'ObettiAmplitude26H1':[],
    'ObettiAmplitude27H1':[],
    'ObettiAmplitude28H1':[],
    'ObettiAmplitude29H1':[],
    'ObettiAmplitude30H1':[],
    'ObettiAmplitude31H1':[],
    'ObettiAmplitude32H1':[],
    'ObettiAmplitude33H1':[],
    'ObettiAmplitude34H1':[],
    'ObettiAmplitude35H1':[],
    'ObettiAmplitude36H1':[],
    'ObettiAmplitude37H1':[],
    'ObettiAmplitude38H1':[],
    'ObettiAmplitude39H1':[],
    'ObettiAmplitude40H1':[],
    'ObettiAmplitude41H1':[],
    'ObettiAmplitude42H1':[],
    'ObettiAmplitude43H1':[],
    'ObettiAmplitude44H1':[],
    'ObettiAmplitude45H1':[],
    'ObettiAmplitude46H1':[],
    'ObettiAmplitude47H1':[],
    'ObettiAmplitude48H1':[],
    'ObettiAmplitude49H1':[],
    'ObettiAmplitude50H1':[],
    'ObettiAmplitude51H1':[],
    'ObettiAmplitude52H1':[],
    'ObettiAmplitude53H1':[],
    'ObettiAmplitude54H1':[],
    'ObettiAmplitude55H1':[],
    'ObettiAmplitude56H1':[],
    'ObettiAmplitude57H1':[],
    'ObettiAmplitude58H1':[],
    'ObettiAmplitude59H1':[],
    'ObettiAmplitude60H1':[],
    'ObettiAmplitude61H1':[],
    'ObettiAmplitude62H1':[],
    'ObettiAmplitude63H1':[],
    'ObettiAmplitude64H1':[],
    'ObettiAmplitude65H1':[],
    'ObettiAmplitude66H1':[],
    'ObettiAmplitude67H1':[],
    'ObettiAmplitude68H1':[],
    'ObettiAmplitude69H1':[],
    'ObettiAmplitude70H1':[],
    'ObettiAmplitude71H1':[],
    'ObettiAmplitude72H1':[],
    'ObettiAmplitude73H1':[],
    'ObettiAmplitude74H1':[],
    'ObettiAmplitude75H1':[],
    'ObettiAmplitude76H1':[],
    'ObettiAmplitude77H1':[],
    'ObettiAmplitude78H1':[],
    'ObettiAmplitude79H1':[],
    'ObettiAmplitude80H1':[],
    'ObettiAmplitude81H1':[],
    'ObettiAmplitude82H1':[],
    'ObettiAmplitude83H1':[],
    'ObettiAmplitude84H1':[],
    'ObettiAmplitude85H1':[],
    'ObettiAmplitude86H1':[],
    'ObettiAmplitude87H1':[],
    'ObettiAmplitude88H1':[],
    'ObettiAmplitude89H1':[],
    'ObettiAmplitude90H1':[],
    'ObettiAmplitude91H1':[],
    'ObettiAmplitude92H1':[],
    'ObettiAmplitude93H1':[],
    'ObettiAmplitude94H1':[],
    'ObettiAmplitude95H1':[],
    'ObettiAmplitude96H1':[],
    'ObettiAmplitude97H1':[],
    'ObettiAmplitude98H1':[],
    'ObettiAmplitude99H1':[],
    'ObettiAmplitude100H1':[],
    'ObettiAmplitude1H2':[],
    'ObettiAmplitude2H2':[],
    'ObettiAmplitude3H2':[],
    'ObettiAmplitude4H2':[],
    'ObettiAmplitude5H2':[],
    'ObettiAmplitude6H2':[],
    'ObettiAmplitude7H2':[],
    'ObettiAmplitude8H2':[],
    'ObettiAmplitude9H2':[],
    'ObettiAmplitude10H2':[],
    'ObettiAmplitude11H2':[],
    'ObettiAmplitude12H2':[],
    'ObettiAmplitude13H2':[],
    'ObettiAmplitude14H2':[],
    'ObettiAmplitude15H2':[],
    'ObettiAmplitude16H2':[],
    'ObettiAmplitude17H2':[],
    'ObettiAmplitude18H2':[],
    'ObettiAmplitude19H2':[],
    'ObettiAmplitude20H2':[],
    'ObettiAmplitude21H2':[],
    'ObettiAmplitude22H2':[],
    'ObettiAmplitude23H2':[],
    'ObettiAmplitude24H2':[],
    'ObettiAmplitude25H2':[],
    'ObettiAmplitude26H2':[],
    'ObettiAmplitude27H2':[],
    'ObettiAmplitude28H2':[],
    'ObettiAmplitude29H2':[],
    'ObettiAmplitude30H2':[],
    'ObettiAmplitude31H2':[],
    'ObettiAmplitude32H2':[],
    'ObettiAmplitude33H2':[],
    'ObettiAmplitude34H2':[],
    'ObettiAmplitude35H2':[],
    'ObettiAmplitude36H2':[],
    'ObettiAmplitude37H2':[],
    'ObettiAmplitude38H2':[],
    'ObettiAmplitude39H2':[],
    'ObettiAmplitude40H2':[],
    'ObettiAmplitude41H2':[],
    'ObettiAmplitude42H2':[],
    'ObettiAmplitude43H2':[],
    'ObettiAmplitude44H2':[],
    'ObettiAmplitude45H2':[],
    'ObettiAmplitude46H2':[],
    'ObettiAmplitude47H2':[],
    'ObettiAmplitude48H2':[],
    'ObettiAmplitude49H2':[],
    'ObettiAmplitude50H2':[],
    'ObettiAmplitude51H2':[],
    'ObettiAmplitude52H2':[],
    'ObettiAmplitude53H2':[],
    'ObettiAmplitude54H2':[],
    'ObettiAmplitude55H2':[],
    'ObettiAmplitude56H2':[],
    'ObettiAmplitude57H2':[],
    'ObettiAmplitude58H2':[],
    'ObettiAmplitude59H2':[],
    'ObettiAmplitude60H2':[],
    'ObettiAmplitude61H2':[],
    'ObettiAmplitude62H2':[],
    'ObettiAmplitude63H2':[],
    'ObettiAmplitude64H2':[],
    'ObettiAmplitude65H2':[],
    'ObettiAmplitude66H2':[],
    'ObettiAmplitude67H2':[],
    'ObettiAmplitude68H2':[],
    'ObettiAmplitude69H2':[],
    'ObettiAmplitude70H2':[],
    'ObettiAmplitude71H2':[],
    'ObettiAmplitude72H2':[],
    'ObettiAmplitude73H2':[],
    'ObettiAmplitude74H2':[],
    'ObettiAmplitude75H2':[],
    'ObettiAmplitude76H2':[],
    'ObettiAmplitude77H2':[],
    'ObettiAmplitude78H2':[],
    'ObettiAmplitude79H2':[],
    'ObettiAmplitude80H2':[],
    'ObettiAmplitude81H2':[],
    'ObettiAmplitude82H2':[],
    'ObettiAmplitude83H2':[],
    'ObettiAmplitude84H2':[],
    'ObettiAmplitude85H2':[],
    'ObettiAmplitude86H2':[],
    'ObettiAmplitude87H2':[],
    'ObettiAmplitude88H2':[],
    'ObettiAmplitude89H2':[],
    'ObettiAmplitude90H2':[],
    'ObettiAmplitude91H2':[],
    'ObettiAmplitude92H2':[],
    'ObettiAmplitude93H2':[],
    'ObettiAmplitude94H2':[],
    'ObettiAmplitude95H2':[],
    'ObettiAmplitude96H2':[],
    'ObettiAmplitude97H2':[],
    'ObettiAmplitude98H2':[],
    'ObettiAmplitude99H2':[],
    'ObettiAmplitude100H2':[],
    'OcomplexPolinomialCoef1H0': [],
    'OcomplexPolinomialCoef2H0': [],
    'OcomplexPolinomialCoef3H0': [],
    'OcomplexPolinomialCoef4H0': [],
    'OcomplexPolinomialCoef5H0': [],
    'OcomplexPolinomialCoef6H0': [],
    'OcomplexPolinomialCoef7H0': [],
    'OcomplexPolinomialCoef8H0': [],
    'OcomplexPolinomialCoef9H0': [],
    'OcomplexPolinomialCoef10H0': [],
    'OcomplexPolinomialCoef1H1': [],
    'OcomplexPolinomialCoef2H1': [],
    'OcomplexPolinomialCoef3H1': [],
    'OcomplexPolinomialCoef4H1': [],
    'OcomplexPolinomialCoef5H1': [],
    'OcomplexPolinomialCoef6H1': [],
    'OcomplexPolinomialCoef7H1': [],
    'OcomplexPolinomialCoef8H1': [],
    'OcomplexPolinomialCoef9H1': [],
    'OcomplexPolinomialCoef10H1': [],
    'OcomplexPolinomialCoef1H2': [],
    'OcomplexPolinomialCoef2H2': [],
    'OcomplexPolinomialCoef3H2': [],
    'OcomplexPolinomialCoef4H2': [],
    'OcomplexPolinomialCoef5H2': [],
    'OcomplexPolinomialCoef6H2': [],
    'OcomplexPolinomialCoef7H2': [],
    'OcomplexPolinomialCoef8H2': [],
    'OcomplexPolinomialCoef9H2': [],
    'OcomplexPolinomialCoef10H2': [],
    'UentropyH0':[],
    'UentropyH1':[],
    'UentropyH2':[],
    'UlandscapeAmplitudeH0':[],
    'UlandscapeAmplitudeH1':[],
    'UlandscapeAmplitudeH2':[],
    'UnumberOfPoints':[],
    'UbettiAmplitude1H0':[],
    'UbettiAmplitude2H0':[],
    'UbettiAmplitude3H0':[],
    'UbettiAmplitude4H0':[],
    'UbettiAmplitude5H0':[],
    'UbettiAmplitude6H0':[],
    'UbettiAmplitude7H0':[],
    'UbettiAmplitude8H0':[],
    'UbettiAmplitude9H0':[],
    'UbettiAmplitude10H0':[],
    'UbettiAmplitude11H0':[],
    'UbettiAmplitude12H0':[],
    'UbettiAmplitude13H0':[],
    'UbettiAmplitude14H0':[],
    'UbettiAmplitude15H0':[],
    'UbettiAmplitude16H0':[],
    'UbettiAmplitude17H0':[],
    'UbettiAmplitude18H0':[],
    'UbettiAmplitude19H0':[],
    'UbettiAmplitude20H0':[],
    'UbettiAmplitude21H0':[],
    'UbettiAmplitude22H0':[],
    'UbettiAmplitude23H0':[],
    'UbettiAmplitude24H0':[],
    'UbettiAmplitude25H0':[],
    'UbettiAmplitude26H0':[],
    'UbettiAmplitude27H0':[],
    'UbettiAmplitude28H0':[],
    'UbettiAmplitude29H0':[],
    'UbettiAmplitude30H0':[],
    'UbettiAmplitude31H0':[],
    'UbettiAmplitude32H0':[],
    'UbettiAmplitude33H0':[],
    'UbettiAmplitude34H0':[],
    'UbettiAmplitude35H0':[],
    'UbettiAmplitude36H0':[],
    'UbettiAmplitude37H0':[],
    'UbettiAmplitude38H0':[],
    'UbettiAmplitude39H0':[],
    'UbettiAmplitude40H0':[],
    'UbettiAmplitude41H0':[],
    'UbettiAmplitude42H0':[],
    'UbettiAmplitude43H0':[],
    'UbettiAmplitude44H0':[],
    'UbettiAmplitude45H0':[],
    'UbettiAmplitude46H0':[],
    'UbettiAmplitude47H0':[],
    'UbettiAmplitude48H0':[],
    'UbettiAmplitude49H0':[],
    'UbettiAmplitude50H0':[],
    'UbettiAmplitude51H0':[],
    'UbettiAmplitude52H0':[],
    'UbettiAmplitude53H0':[],
    'UbettiAmplitude54H0':[],
    'UbettiAmplitude55H0':[],
    'UbettiAmplitude56H0':[],
    'UbettiAmplitude57H0':[],
    'UbettiAmplitude58H0':[],
    'UbettiAmplitude59H0':[],
    'UbettiAmplitude60H0':[],
    'UbettiAmplitude61H0':[],
    'UbettiAmplitude62H0':[],
    'UbettiAmplitude63H0':[],
    'UbettiAmplitude64H0':[],
    'UbettiAmplitude65H0':[],
    'UbettiAmplitude66H0':[],
    'UbettiAmplitude67H0':[],
    'UbettiAmplitude68H0':[],
    'UbettiAmplitude69H0':[],
    'UbettiAmplitude70H0':[],
    'UbettiAmplitude71H0':[],
    'UbettiAmplitude72H0':[],
    'UbettiAmplitude73H0':[],
    'UbettiAmplitude74H0':[],
    'UbettiAmplitude75H0':[],
    'UbettiAmplitude76H0':[],
    'UbettiAmplitude77H0':[],
    'UbettiAmplitude78H0':[],
    'UbettiAmplitude79H0':[],
    'UbettiAmplitude80H0':[],
    'UbettiAmplitude81H0':[],
    'UbettiAmplitude82H0':[],
    'UbettiAmplitude83H0':[],
    'UbettiAmplitude84H0':[],
    'UbettiAmplitude85H0':[],
    'UbettiAmplitude86H0':[],
    'UbettiAmplitude87H0':[],
    'UbettiAmplitude88H0':[],
    'UbettiAmplitude89H0':[],
    'UbettiAmplitude90H0':[],
    'UbettiAmplitude91H0':[],
    'UbettiAmplitude92H0':[],
    'UbettiAmplitude93H0':[],
    'UbettiAmplitude94H0':[],
    'UbettiAmplitude95H0':[],
    'UbettiAmplitude96H0':[],
    'UbettiAmplitude97H0':[],
    'UbettiAmplitude98H0':[],
    'UbettiAmplitude99H0':[],
    'UbettiAmplitude100H0':[],
    'UbettiAmplitude1H1':[],
    'UbettiAmplitude2H1':[],
    'UbettiAmplitude3H1':[],
    'UbettiAmplitude4H1':[],
    'UbettiAmplitude5H1':[],
    'UbettiAmplitude6H1':[],
    'UbettiAmplitude7H1':[],
    'UbettiAmplitude8H1':[],
    'UbettiAmplitude9H1':[],
    'UbettiAmplitude10H1':[],
    'UbettiAmplitude11H1':[],
    'UbettiAmplitude12H1':[],
    'UbettiAmplitude13H1':[],
    'UbettiAmplitude14H1':[],
    'UbettiAmplitude15H1':[],
    'UbettiAmplitude16H1':[],
    'UbettiAmplitude17H1':[],
    'UbettiAmplitude18H1':[],
    'UbettiAmplitude19H1':[],
    'UbettiAmplitude20H1':[],
    'UbettiAmplitude21H1':[],
    'UbettiAmplitude22H1':[],
    'UbettiAmplitude23H1':[],
    'UbettiAmplitude24H1':[],
    'UbettiAmplitude25H1':[],
    'UbettiAmplitude26H1':[],
    'UbettiAmplitude27H1':[],
    'UbettiAmplitude28H1':[],
    'UbettiAmplitude29H1':[],
    'UbettiAmplitude30H1':[],
    'UbettiAmplitude31H1':[],
    'UbettiAmplitude32H1':[],
    'UbettiAmplitude33H1':[],
    'UbettiAmplitude34H1':[],
    'UbettiAmplitude35H1':[],
    'UbettiAmplitude36H1':[],
    'UbettiAmplitude37H1':[],
    'UbettiAmplitude38H1':[],
    'UbettiAmplitude39H1':[],
    'UbettiAmplitude40H1':[],
    'UbettiAmplitude41H1':[],
    'UbettiAmplitude42H1':[],
    'UbettiAmplitude43H1':[],
    'UbettiAmplitude44H1':[],
    'UbettiAmplitude45H1':[],
    'UbettiAmplitude46H1':[],
    'UbettiAmplitude47H1':[],
    'UbettiAmplitude48H1':[],
    'UbettiAmplitude49H1':[],
    'UbettiAmplitude50H1':[],
    'UbettiAmplitude51H1':[],
    'UbettiAmplitude52H1':[],
    'UbettiAmplitude53H1':[],
    'UbettiAmplitude54H1':[],
    'UbettiAmplitude55H1':[],
    'UbettiAmplitude56H1':[],
    'UbettiAmplitude57H1':[],
    'UbettiAmplitude58H1':[],
    'UbettiAmplitude59H1':[],
    'UbettiAmplitude60H1':[],
    'UbettiAmplitude61H1':[],
    'UbettiAmplitude62H1':[],
    'UbettiAmplitude63H1':[],
    'UbettiAmplitude64H1':[],
    'UbettiAmplitude65H1':[],
    'UbettiAmplitude66H1':[],
    'UbettiAmplitude67H1':[],
    'UbettiAmplitude68H1':[],
    'UbettiAmplitude69H1':[],
    'UbettiAmplitude70H1':[],
    'UbettiAmplitude71H1':[],
    'UbettiAmplitude72H1':[],
    'UbettiAmplitude73H1':[],
    'UbettiAmplitude74H1':[],
    'UbettiAmplitude75H1':[],
    'UbettiAmplitude76H1':[],
    'UbettiAmplitude77H1':[],
    'UbettiAmplitude78H1':[],
    'UbettiAmplitude79H1':[],
    'UbettiAmplitude80H1':[],
    'UbettiAmplitude81H1':[],
    'UbettiAmplitude82H1':[],
    'UbettiAmplitude83H1':[],
    'UbettiAmplitude84H1':[],
    'UbettiAmplitude85H1':[],
    'UbettiAmplitude86H1':[],
    'UbettiAmplitude87H1':[],
    'UbettiAmplitude88H1':[],
    'UbettiAmplitude89H1':[],
    'UbettiAmplitude90H1':[],
    'UbettiAmplitude91H1':[],
    'UbettiAmplitude92H1':[],
    'UbettiAmplitude93H1':[],
    'UbettiAmplitude94H1':[],
    'UbettiAmplitude95H1':[],
    'UbettiAmplitude96H1':[],
    'UbettiAmplitude97H1':[],
    'UbettiAmplitude98H1':[],
    'UbettiAmplitude99H1':[],
    'UbettiAmplitude100H1':[],
    'UbettiAmplitude1H2':[],
    'UbettiAmplitude2H2':[],
    'UbettiAmplitude3H2':[],
    'UbettiAmplitude4H2':[],
    'UbettiAmplitude5H2':[],
    'UbettiAmplitude6H2':[],
    'UbettiAmplitude7H2':[],
    'UbettiAmplitude8H2':[],
    'UbettiAmplitude9H2':[],
    'UbettiAmplitude10H2':[],
    'UbettiAmplitude11H2':[],
    'UbettiAmplitude12H2':[],
    'UbettiAmplitude13H2':[],
    'UbettiAmplitude14H2':[],
    'UbettiAmplitude15H2':[],
    'UbettiAmplitude16H2':[],
    'UbettiAmplitude17H2':[],
    'UbettiAmplitude18H2':[],
    'UbettiAmplitude19H2':[],
    'UbettiAmplitude20H2':[],
    'UbettiAmplitude21H2':[],
    'UbettiAmplitude22H2':[],
    'UbettiAmplitude23H2':[],
    'UbettiAmplitude24H2':[],
    'UbettiAmplitude25H2':[],
    'UbettiAmplitude26H2':[],
    'UbettiAmplitude27H2':[],
    'UbettiAmplitude28H2':[],
    'UbettiAmplitude29H2':[],
    'UbettiAmplitude30H2':[],
    'UbettiAmplitude31H2':[],
    'UbettiAmplitude32H2':[],
    'UbettiAmplitude33H2':[],
    'UbettiAmplitude34H2':[],
    'UbettiAmplitude35H2':[],
    'UbettiAmplitude36H2':[],
    'UbettiAmplitude37H2':[],
    'UbettiAmplitude38H2':[],
    'UbettiAmplitude39H2':[],
    'UbettiAmplitude40H2':[],
    'UbettiAmplitude41H2':[],
    'UbettiAmplitude42H2':[],
    'UbettiAmplitude43H2':[],
    'UbettiAmplitude44H2':[],
    'UbettiAmplitude45H2':[],
    'UbettiAmplitude46H2':[],
    'UbettiAmplitude47H2':[],
    'UbettiAmplitude48H2':[],
    'UbettiAmplitude49H2':[],
    'UbettiAmplitude50H2':[],
    'UbettiAmplitude51H2':[],
    'UbettiAmplitude52H2':[],
    'UbettiAmplitude53H2':[],
    'UbettiAmplitude54H2':[],
    'UbettiAmplitude55H2':[],
    'UbettiAmplitude56H2':[],
    'UbettiAmplitude57H2':[],
    'UbettiAmplitude58H2':[],
    'UbettiAmplitude59H2':[],
    'UbettiAmplitude60H2':[],
    'UbettiAmplitude61H2':[],
    'UbettiAmplitude62H2':[],
    'UbettiAmplitude63H2':[],
    'UbettiAmplitude64H2':[],
    'UbettiAmplitude65H2':[],
    'UbettiAmplitude66H2':[],
    'UbettiAmplitude67H2':[],
    'UbettiAmplitude68H2':[],
    'UbettiAmplitude69H2':[],
    'UbettiAmplitude70H2':[],
    'UbettiAmplitude71H2':[],
    'UbettiAmplitude72H2':[],
    'UbettiAmplitude73H2':[],
    'UbettiAmplitude74H2':[],
    'UbettiAmplitude75H2':[],
    'UbettiAmplitude76H2':[],
    'UbettiAmplitude77H2':[],
    'UbettiAmplitude78H2':[],
    'UbettiAmplitude79H2':[],
    'UbettiAmplitude80H2':[],
    'UbettiAmplitude81H2':[],
    'UbettiAmplitude82H2':[],
    'UbettiAmplitude83H2':[],
    'UbettiAmplitude84H2':[],
    'UbettiAmplitude85H2':[],
    'UbettiAmplitude86H2':[],
    'UbettiAmplitude87H2':[],
    'UbettiAmplitude88H2':[],
    'UbettiAmplitude89H2':[],
    'UbettiAmplitude90H2':[],
    'UbettiAmplitude91H2':[],
    'UbettiAmplitude92H2':[],
    'UbettiAmplitude93H2':[],
    'UbettiAmplitude94H2':[],
    'UbettiAmplitude95H2':[],
    'UbettiAmplitude96H2':[],
    'UbettiAmplitude97H2':[],
    'UbettiAmplitude98H2':[],
    'UbettiAmplitude99H2':[],
    'UbettiAmplitude100H2':[],
    'UcomplexPolinomialCoef1H0': [],
    'UcomplexPolinomialCoef2H0': [],
    'UcomplexPolinomialCoef3H0': [],
    'UcomplexPolinomialCoef4H0': [],
    'UcomplexPolinomialCoef5H0': [],
    'UcomplexPolinomialCoef6H0': [],
    'UcomplexPolinomialCoef7H0': [],
    'UcomplexPolinomialCoef8H0': [],
    'UcomplexPolinomialCoef9H0': [],
    'UcomplexPolinomialCoef10H0': [],
    'UcomplexPolinomialCoef1H1': [],
    'UcomplexPolinomialCoef2H1': [],
    'UcomplexPolinomialCoef3H1': [],
    'UcomplexPolinomialCoef4H1': [],
    'UcomplexPolinomialCoef5H1': [],
    'UcomplexPolinomialCoef6H1': [],
    'UcomplexPolinomialCoef7H1': [],
    'UcomplexPolinomialCoef8H1': [],
    'UcomplexPolinomialCoef9H1': [],
    'UcomplexPolinomialCoef10H1': [],
    'UcomplexPolinomialCoef1H2': [],
    'UcomplexPolinomialCoef2H2': [],
    'UcomplexPolinomialCoef3H2': [],
    'UcomplexPolinomialCoef4H2': [],
    'UcomplexPolinomialCoef5H2': [],
    'UcomplexPolinomialCoef6H2': [],
    'UcomplexPolinomialCoef7H2': [],
    'UcomplexPolinomialCoef8H2': [],
    'UcomplexPolinomialCoef9H2': [],
    'UcomplexPolinomialCoef10H2': [],

}
featuresWithoutBettiPoints = {
    'sampleName': [],
    'parkinson?':[],
    # 'AInfinitePointsH0':[],
    # 'AInfinitePointsH1':[],
    # 'AInfinitePointsH2':[],
    'AentropyH0':[],
    'AentropyH1':[],
    'AentropyH2':[],
    'AlandscapeAmplitudeH0':[],
    'AlandscapeAmplitudeH1':[],
    'AlandscapeAmplitudeH2':[],
    'AnumberOfPointsH0':[],
    'AnumberOfPointsH1':[],
    'AnumberOfPointsH2':[],
    'AbettiAmplitudeH0':[],
    'AbettiAmplitudeH1':[],
    'AbettiAmplitudeH2':[],
    'AcomplexPolinomialCoef1H0': [],
    'AcomplexPolinomialCoef2H0': [],
    'AcomplexPolinomialCoef3H0': [],
    'AcomplexPolinomialCoef4H0': [],
    'AcomplexPolinomialCoef5H0': [],
    'AcomplexPolinomialCoef6H0': [],
    'AcomplexPolinomialCoef7H0': [],
    'AcomplexPolinomialCoef8H0': [],
    'AcomplexPolinomialCoef9H0': [],
    'AcomplexPolinomialCoef10H0': [],
    'AcomplexPolinomialCoef1H1': [],
    'AcomplexPolinomialCoef2H1': [],
    'AcomplexPolinomialCoef3H1': [],
    'AcomplexPolinomialCoef4H1': [],
    'AcomplexPolinomialCoef5H1': [],
    'AcomplexPolinomialCoef6H1': [],
    'AcomplexPolinomialCoef7H1': [],
    'AcomplexPolinomialCoef8H1': [],
    'AcomplexPolinomialCoef9H1': [],
    'AcomplexPolinomialCoef10H1': [],
    'AcomplexPolinomialCoef1H2': [],
    'AcomplexPolinomialCoef2H2': [],
    'AcomplexPolinomialCoef3H2': [],
    'AcomplexPolinomialCoef4H2': [],
    'AcomplexPolinomialCoef5H2': [],
    'AcomplexPolinomialCoef6H2': [],
    'AcomplexPolinomialCoef7H2': [],
    'AcomplexPolinomialCoef8H2': [],
    'AcomplexPolinomialCoef9H2': [],
    'AcomplexPolinomialCoef10H2': [],
    # 'EInfinitePointsH0':[],
    # 'EInfinitePointsH1':[],
    # 'EInfinitePointsH2':[],
    'EentropyH0':[],
    'EentropyH1':[],
    'EentropyH2':[],
    'ElandscapeAmplitudeH0':[],
    'ElandscapeAmplitudeH1':[],
    'ElandscapeAmplitudeH2':[],
    'EnumberOfPointsH0':[],
    'EnumberOfPointsH1':[],
    'EnumberOfPointsH2':[],
    'EbettiAmplitudeH0':[],
    'EbettiAmplitudeH1':[],
    'EbettiAmplitudeH2':[],
    'EcomplexPolinomialCoef1H0': [],
    'EcomplexPolinomialCoef2H0': [],
    'EcomplexPolinomialCoef3H0': [],
    'EcomplexPolinomialCoef4H0': [],
    'EcomplexPolinomialCoef5H0': [],
    'EcomplexPolinomialCoef6H0': [],
    'EcomplexPolinomialCoef7H0': [],
    'EcomplexPolinomialCoef8H0': [],
    'EcomplexPolinomialCoef9H0': [],
    'EcomplexPolinomialCoef10H0': [],
    'EcomplexPolinomialCoef1H1': [],
    'EcomplexPolinomialCoef2H1': [],
    'EcomplexPolinomialCoef3H1': [],
    'EcomplexPolinomialCoef4H1': [],
    'EcomplexPolinomialCoef5H1': [],
    'EcomplexPolinomialCoef6H1': [],
    'EcomplexPolinomialCoef7H1': [],
    'EcomplexPolinomialCoef8H1': [],
    'EcomplexPolinomialCoef9H1': [],
    'EcomplexPolinomialCoef10H1': [],
    'EcomplexPolinomialCoef1H2': [],
    'EcomplexPolinomialCoef2H2': [],
    'EcomplexPolinomialCoef3H2': [],
    'EcomplexPolinomialCoef4H2': [],
    'EcomplexPolinomialCoef5H2': [],
    'EcomplexPolinomialCoef6H2': [],
    'EcomplexPolinomialCoef7H2': [],
    'EcomplexPolinomialCoef8H2': [],
    'EcomplexPolinomialCoef9H2': [],
    'EcomplexPolinomialCoef10H2': [],
    # 'IInfinitePointsH0':[],
    # 'IInfinitePointsH1':[],
    # 'IInfinitePointsH2':[],

    'IentropyH0':[],
    'IentropyH1':[],
    'IentropyH2':[],
    'IlandscapeAmplitudeH0':[],
    'IlandscapeAmplitudeH1':[],
    'IlandscapeAmplitudeH2':[],
    'InumberOfPointsH0':[],
    'InumberOfPointsH1':[],
    'InumberOfPointsH2':[],
    
    'IbettiAmplitudeH0':[],
    'IbettiAmplitudeH1':[],
    'IbettiAmplitudeH2':[],
    'IcomplexPolinomialCoef1H0': [],
    'IcomplexPolinomialCoef2H0': [],
    'IcomplexPolinomialCoef3H0': [],
    'IcomplexPolinomialCoef4H0': [],
    'IcomplexPolinomialCoef5H0': [],
    'IcomplexPolinomialCoef6H0': [],
    'IcomplexPolinomialCoef7H0': [],
    'IcomplexPolinomialCoef8H0': [],
    'IcomplexPolinomialCoef9H0': [],
    'IcomplexPolinomialCoef10H0': [],
    'IcomplexPolinomialCoef1H1': [],
    'IcomplexPolinomialCoef2H1': [],
    'IcomplexPolinomialCoef3H1': [],
    'IcomplexPolinomialCoef4H1': [],
    'IcomplexPolinomialCoef5H1': [],
    'IcomplexPolinomialCoef6H1': [],
    'IcomplexPolinomialCoef7H1': [],
    'IcomplexPolinomialCoef8H1': [],
    'IcomplexPolinomialCoef9H1': [],
    'IcomplexPolinomialCoef10H1': [],
    'IcomplexPolinomialCoef1H2': [],
    'IcomplexPolinomialCoef2H2': [],
    'IcomplexPolinomialCoef3H2': [],
    'IcomplexPolinomialCoef4H2': [],
    'IcomplexPolinomialCoef5H2': [],
    'IcomplexPolinomialCoef6H2': [],
    'IcomplexPolinomialCoef7H2': [],
    'IcomplexPolinomialCoef8H2': [],
    'IcomplexPolinomialCoef9H2': [],
    'IcomplexPolinomialCoef10H2': [],
    # 'OInfinitePointsH0':[],
    # 'OInfinitePointsH1':[],
    # 'OInfinitePointsH2':[],
    'OentropyH0':[],
    'OentropyH1':[],
    'OentropyH2':[],
    'OlandscapeAmplitudeH0':[],
    'OlandscapeAmplitudeH1':[],
    'OlandscapeAmplitudeH2':[],
    'OnumberOfPointsH0':[],
    'OnumberOfPointsH1':[],
    'OnumberOfPointsH2':[],
    
    'ObettiAmplitudeH0':[],
    'ObettiAmplitudeH1':[],
    'ObettiAmplitudeH2':[],
    'OcomplexPolinomialCoef1H0': [],
    'OcomplexPolinomialCoef2H0': [],
    'OcomplexPolinomialCoef3H0': [],
    'OcomplexPolinomialCoef4H0': [],
    'OcomplexPolinomialCoef5H0': [],
    'OcomplexPolinomialCoef6H0': [],
    'OcomplexPolinomialCoef7H0': [],
    'OcomplexPolinomialCoef8H0': [],
    'OcomplexPolinomialCoef9H0': [],
    'OcomplexPolinomialCoef10H0': [],
    'OcomplexPolinomialCoef1H1': [],
    'OcomplexPolinomialCoef2H1': [],
    'OcomplexPolinomialCoef3H1': [],
    'OcomplexPolinomialCoef4H1': [],
    'OcomplexPolinomialCoef5H1': [],
    'OcomplexPolinomialCoef6H1': [],
    'OcomplexPolinomialCoef7H1': [],
    'OcomplexPolinomialCoef8H1': [],
    'OcomplexPolinomialCoef9H1': [],
    'OcomplexPolinomialCoef10H1': [],
    'OcomplexPolinomialCoef1H2': [],
    'OcomplexPolinomialCoef2H2': [],
    'OcomplexPolinomialCoef3H2': [],
    'OcomplexPolinomialCoef4H2': [],
    'OcomplexPolinomialCoef5H2': [],
    'OcomplexPolinomialCoef6H2': [],
    'OcomplexPolinomialCoef7H2': [],
    'OcomplexPolinomialCoef8H2': [],
    'OcomplexPolinomialCoef9H2': [],
    'OcomplexPolinomialCoef10H2': [],
    # 'UInfinitePointsH0':[],
    # 'UInfinitePointsH1':[],
    # 'UInfinitePointsH2':[],
    'UentropyH0':[],
    'UentropyH1':[],
    'UentropyH2':[],
    'UlandscapeAmplitudeH0':[],
    'UlandscapeAmplitudeH1':[],
    'UlandscapeAmplitudeH2':[],
    'UnumberOfPointsH0':[],
    'UnumberOfPointsH1':[],    
    'UnumberOfPointsH2':[],
    'UbettiAmplitudeH0':[],
    'UbettiAmplitudeH1':[],
    'UbettiAmplitudeH2':[],
    'UcomplexPolinomialCoef1H0': [],
    'UcomplexPolinomialCoef2H0': [],
    'UcomplexPolinomialCoef3H0': [],
    'UcomplexPolinomialCoef4H0': [],
    'UcomplexPolinomialCoef5H0': [],
    'UcomplexPolinomialCoef6H0': [],
    'UcomplexPolinomialCoef7H0': [],
    'UcomplexPolinomialCoef8H0': [],
    'UcomplexPolinomialCoef9H0': [],
    'UcomplexPolinomialCoef10H0': [],
    'UcomplexPolinomialCoef1H1': [],
    'UcomplexPolinomialCoef2H1': [],
    'UcomplexPolinomialCoef3H1': [],
    'UcomplexPolinomialCoef4H1': [],
    'UcomplexPolinomialCoef5H1': [],
    'UcomplexPolinomialCoef6H1': [],
    'UcomplexPolinomialCoef7H1': [],
    'UcomplexPolinomialCoef8H1': [],
    'UcomplexPolinomialCoef9H1': [],
    'UcomplexPolinomialCoef10H1': [],
    'UcomplexPolinomialCoef1H2': [],
    'UcomplexPolinomialCoef2H2': [],
    'UcomplexPolinomialCoef3H2': [],
    'UcomplexPolinomialCoef4H2': [],
    'UcomplexPolinomialCoef5H2': [],
    'UcomplexPolinomialCoef6H2': [],
    'UcomplexPolinomialCoef7H2': [],
    'UcomplexPolinomialCoef8H2': [],
    'UcomplexPolinomialCoef9H2': [],
    'UcomplexPolinomialCoef10H2': [],
}
uFeatures = {
        'sampleName': [],
    'parkinson?':[],
        'UentropyH0':[],
    'UentropyH1':[],
    'UentropyH2':[],
    'UlandscapeAmplitudeH0':[],
    'UlandscapeAmplitudeH1':[],
    'UlandscapeAmplitudeH2':[],
    'UnumberOfPointsH0':[],
    'UnumberOfPointsH1':[],    
    'UnumberOfPointsH2':[],
    'UbettiAmplitudeH0':[],
    'UbettiAmplitudeH1':[],
    'UbettiAmplitudeH2':[],
    'UcomplexPolinomialCoef1H0': [],
    'UcomplexPolinomialCoef2H0': [],
    'UcomplexPolinomialCoef3H0': [],
    'UcomplexPolinomialCoef4H0': [],
    'UcomplexPolinomialCoef5H0': [],
    'UcomplexPolinomialCoef6H0': [],
    'UcomplexPolinomialCoef7H0': [],
    'UcomplexPolinomialCoef8H0': [],
    'UcomplexPolinomialCoef9H0': [],
    'UcomplexPolinomialCoef10H0': [],
    'UcomplexPolinomialCoef1H1': [],
    'UcomplexPolinomialCoef2H1': [],
    'UcomplexPolinomialCoef3H1': [],
    'UcomplexPolinomialCoef4H1': [],
    'UcomplexPolinomialCoef5H1': [],
    'UcomplexPolinomialCoef6H1': [],
    'UcomplexPolinomialCoef7H1': [],
    'UcomplexPolinomialCoef8H1': [],
    'UcomplexPolinomialCoef9H1': [],
    'UcomplexPolinomialCoef10H1': [],
    'UcomplexPolinomialCoef1H2': [],
    'UcomplexPolinomialCoef2H2': [],
    'UcomplexPolinomialCoef3H2': [],
    'UcomplexPolinomialCoef4H2': [],
    'UcomplexPolinomialCoef5H2': [],
    'UcomplexPolinomialCoef6H2': [],
    'UcomplexPolinomialCoef7H2': [],
    'UcomplexPolinomialCoef8H2': [],
    'UcomplexPolinomialCoef9H2': [],
    'UcomplexPolinomialCoef10H2': [],
}

featuresDf = pd.DataFrame(uFeatures)
def tranformDataForGiotto(data, infinitePoints):
    giottoFittedData = []
    for row in data:
        dimension = int(row[2])
        if(len(giottoFittedData) <= dimension):
           giottoFittedData.insert(dimension, [])
        if row[1] == np.inf:
            infinitePoints[dimension] += 1
            continue
            # row[1] = maxDistance 
        giottoFittedData[dimension].append(row)
    return [np.array(diagram) for diagram in giottoFittedData]

for labelDirectoryName in os.listdir(directory):
    print(f"Starting with directory {labelDirectoryName}")
    parkinson = 1
    if(labelDirectoryName == 'Control'):
        parkinson = 0
    directoryWithLabel = directory + "/" + labelDirectoryName
    vocalDirectories =  os.listdir(directoryWithLabel)
    fullVocalDirectories = [directoryWithLabel + "/U"]
    allFiles = [os.listdir(fullDirectory) for fullDirectory in fullVocalDirectories]
    for fileIndex in range(0,len(allFiles[0])):
        rowToInsert = []
        error = False
        sampleName = allFiles[0][fileIndex].split("Persistence")[0]
        rowToInsert.append(sampleName)
        rowToInsert.append(parkinson)
        for directoryIndex in range(0,len(fullVocalDirectories)):
            f = os.path.join(fullVocalDirectories[directoryIndex], allFiles[directoryIndex][fileIndex])
            persistence_diagrams = np.loadtxt(f,delimiter=",", dtype=np.float64, skiprows=1)
            infinitePoints = [0,0,0]
            giottoPersistenceDiagrams = tranformDataForGiotto(persistence_diagrams, infinitePoints)
            if len(giottoPersistenceDiagrams) != 3:
                error = True
                break
            # The infinitePoints are inserted
            # rowToInsert.append(infinitePoints[0]) #Dimension 0
            # rowToInsert.append(infinitePoints[1]) #Dimension 1
            # rowToInsert.append(infinitePoints[2]) #Dimension 2
            
            # Metrics: 'bottleneck' | 'wasserstein' | 'betti' | 'landscape' | 'silhouette' | 'heat' | 'persistence_image'
            landscapeAmplitude = Amplitude(metric='landscape')
            # Default is 2 floats and 100 bins
            # Devuelve la suma de las distancias entre cada punto, no la distancia entre ellos 
            bettiAmplitude = Amplitude(metric='betti', metric_params={'p': 2,'n_bins':100 }) 
            persistenceEntropy = PersistenceEntropy()
            complexPolynomial = ComplexPolynomial(n_coefficients=5, n_jobs=1)
            persistenceEntropy0 = persistenceEntropy.fit_transform([giottoPersistenceDiagrams[0]])[0]
            rowToInsert.append(persistenceEntropy0[0])
            persistenceEntropy1 = persistenceEntropy.fit_transform([giottoPersistenceDiagrams[1]])[0]
            rowToInsert.append(persistenceEntropy1[0])
            persistenceEntropy2 = persistenceEntropy.fit_transform([giottoPersistenceDiagrams[2]])[0]
            rowToInsert.append(persistenceEntropy2[0])
            landscapeAmplitudeDim0 = landscapeAmplitude.fit_transform([giottoPersistenceDiagrams[0]])[0]
            rowToInsert.append(landscapeAmplitudeDim0[0])
            landscapeAmplitudeDim1 = landscapeAmplitude.fit_transform([giottoPersistenceDiagrams[1]])[0]
            rowToInsert.append(landscapeAmplitudeDim1[0])
            landscapeAmplitudeDim2 = landscapeAmplitude.fit_transform([giottoPersistenceDiagrams[2]])[0]
            rowToInsert.append(landscapeAmplitudeDim2[0])
            numberOfPoints = NumberOfPoints(n_jobs=-1)
            numberOfPointsDim0 = numberOfPoints.fit_transform([giottoPersistenceDiagrams[0]])[0]
            rowToInsert.append(numberOfPointsDim0[0])
            numberOfPointsDim1 = numberOfPoints.fit_transform([giottoPersistenceDiagrams[1]])[0]
            rowToInsert.append(numberOfPointsDim1[0])
            numberOfPointsDim2 = numberOfPoints.fit_transform([giottoPersistenceDiagrams[2]])[0]
            rowToInsert.append(numberOfPointsDim2[0])
            bettiAmplitude0 = bettiAmplitude.fit_transform([giottoPersistenceDiagrams[0]])[0]
            rowToInsert.append(bettiAmplitude0[0])
            bettiAmplitude1 = bettiAmplitude.fit_transform([giottoPersistenceDiagrams[1]])[0]
            rowToInsert.append(bettiAmplitude1[0])
            bettiAmplitude2 = bettiAmplitude.fit_transform([giottoPersistenceDiagrams[2]])[0]
            rowToInsert.append(bettiAmplitude2[0])
            
            complexPolynomial0 = complexPolynomial.fit_transform([giottoPersistenceDiagrams[0]])[0]
            for coef in complexPolynomial0:
                rowToInsert.append(coef)
            complexPolynomial1 = complexPolynomial.fit_transform([giottoPersistenceDiagrams[1]])[0]
            for coef in complexPolynomial1:
                rowToInsert.append(coef)
            complexPolynomial2 = complexPolynomial.fit_transform([giottoPersistenceDiagrams[2]])[0]
            for coef in complexPolynomial2:
                rowToInsert.append(coef)
        if(not error):
            featuresDf.loc[len(featuresDf)] = rowToInsert
featuresDf.to_csv(savingDirectory, index=False)

            